[package]
name = "pe_inspector"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = [
        "./um",
        "./shared"
]

[package.metadata.wdk.driver-model]
driver-type = "WDM"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
wdk-build = "0.5.1"

[dependencies]
wdk = "0.4.1"
wdk-alloc = "0.4.1"
wdk-panic = "0.4.1"
wdk-sys = "0.5.1"
shared = { path = "shared/" }

[features]
default = []
nightly = ["wdk/nightly", "wdk-sys/nightly"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
