[config]
default_to_workspace = false

[env.development]
TARGET_DIR = "target/debug/"

[task.build]
script = [ "cargo b --all" ]

[tasks.rename]
dependencies = ["build"]
script = ["cd %TARGET_DIR%" , "del pe_inspector.sys", "rename pe_inspector.dll pe_inspector.sys"]

[tasks.all]
script = [ "cargo b --all --examples"]
dependencies = ["rename"]
