#![allow(non_camel_case_types)]

use super::result::Result;
use wdk_sys::ntddk::IoGetCurrentProcess;
use wdk_sys::{HANDLE, LIST_ENTRY, PEPROCESS, PPEB, PVOID, STATUS_SUCCESS, UNICODE_STRING};

struct Process(PEPROCESS);

impl Process {
    pub fn get_peb(&self) -> PPEB {
        unsafe {
            self.0
                .byte_offset(EProcessOffset::Peb as isize)
                .cast::<PPEB>()
                .read()
        }
    }
}

pub fn from_name(process_name: &UNICODE_STRING) -> Result<()> {
    let process = Process(unsafe { IoGetCurrentProcess() });

    let peb = process.get_peb();

    let params = unsafe {
        peb.byte_offset(PebOffset::ProcessParameters as isize)
            .cast::<*mut RTL_USER_PROCESS_PARAMETERS>()
            .read()
    };

    let name = unsafe { params.as_ref_unchecked().image_path_name };

    let list_entry = unsafe {
        process
            .0
            .byte_offset(KProcessOffset::ProcessListEntry as isize)
            .cast::<LIST_ENTRY>()
            .as_ref_unchecked()
    };

    let next_process = unsafe {
        list_entry
            .Flink
            .cast::<*mut LIST_ENTRY>()
            .read()
            .byte_offset(!(KProcessOffset::ProcessListEntry as isize))
            .cast::<PEPROCESS>()
    };

    Result::Status(STATUS_SUCCESS)
}

#[repr(isize)]
pub enum KProcessOffset {
    Header = 0x000,
    ProfileListHead = 0x018, // _LIST_ENTRY
    DirectoryTableBase = 0x028,
    ThreadListHead = 0x030,
    ProcessLock = 0x040,
    ProcessTimerDelay = 0x044,
    DeepFreezeStartTime = 0x048,
    Affinity = 0x050,
    AutoBoostState = 0x058,
    ReadyListHead = 0x068,
    SwapListEntry = 0x078,
    ActiveProcessors = 0x080,
    ProcessFlags = 0x088,
    Spare0c = 0x08c,
    BasePriority = 0x090,
    QuantumReset = 0x091,
    Visited = 0x092,
    Flags = 0x093,
    ActiveGroupsMask = 0x098,
    ActiveGroupPadding = 0x0a8,
    IdealProcessorAssignmentBlock = 0x0b8,
    Padding = 0x0c0,
    Padding2 = 0x0f0,
    SchedulerAssistYieldBoostCount = 0x0f4,
    SchedulerAssistYieldBoostAllowedTime = 0x0f8,
    Spare0d = 0x100,
    IdealGlobalNode = 0x104,
    Spare1 = 0x106,
    StackCount = 0x108,
    ProcessListEntry = 0x110, // _LIST_ENTRY
    CycleTime = 0x120,
    ContextSwitches = 0x128,
    SchedulingGroup = 0x130,
    KernelTime = 0x138,
    UserTime = 0x140,
    ReadyTime = 0x148,
    FreezeCount = 0x150,
    Spare4 = 0x154,
    UserDirectoryTableBase = 0x158,
    AddressPolicy = 0x160,
    Spare2 = 0x161,
    InstrumentationCallback = 0x168,
    SecureState = 0x170,
    KernelWaitTime = 0x178,
    UserWaitTime = 0x180,
    LastRebalanceQpc = 0x188,
    PerProcessorCycleTimes = 0x190,
    ExtendedFeatureDisableMask = 0x198,
    PrimaryGroup = 0x1a0,
    Spare3 = 0x1a2,
    UserCetLogging = 0x1a8,
    CpuPartitionList = 0x1b0,
    AvailableCpuState = 0x1c0,
}

#[repr(isize)]
pub enum EProcessOffset {
    Pcb = 0x000,
    ProcessLock = 0x1c8,
    UniqueProcessId = 0x1d0,
    ActiveProcessLinks = 0x1d8,
    RundownProtect = 0x1e8,
    Flags2 = 0x1f0,
    Flags = 0x1f4,
    CreateTime = 0x1f8,
    ProcessQuotaUsage = 0x200,
    ProcessQuotaPeak = 0x210,
    PeakVirtualSize = 0x220,
    VirtualSize = 0x228,
    SessionProcessLinks = 0x230,
    ExceptionPortData = 0x240,
    Token = 0x248,
    MmReserved = 0x250,
    AddressCreationLock = 0x258,
    PageTableCommitmentLock = 0x260,
    RotateInProgress = 0x268,
    ForkInProgress = 0x270,
    CommitChargeJob = 0x278,
    CloneRoot = 0x280,
    NumberOfPrivatePages = 0x288,
    MmReserved2 = 0x290,
    Win32Process = 0x298,
    Job = 0x2a0,
    SectionObject = 0x2a8,
    SectionBaseAddress = 0x2b0,
    Cookie = 0x2b8,
    WorkingSetWatch = 0x2c0,
    Win32WindowStation = 0x2c8,
    InheritedFromUniqueProcessId = 0x2d0,
    OwnerProcessId = 0x2d8,
    Peb = 0x2e0,
    Session = 0x2e8,
    Spare1 = 0x2f0,
    QuotaBlock = 0x2f8,
    ObjectTable = 0x300,
    DebugPort = 0x308,
    WoW64Process = 0x310,
    DeviceMap = 0x318,
    EtwDataSource = 0x320,
    PageDirectoryPte = 0x328,
    ImageFilePointer = 0x330,
    ImageFileName = 0x338,
    PriorityClass = 0x347,
    SecurityPort = 0x348,
    SeAuditProcessCreationInfo = 0x350,
    JobLinks = 0x358,
    HighestUserAddress = 0x368,
    ThreadListHead = 0x370,
    ActiveThreads = 0x380,
    ImagePathHash = 0x384,
    DefaultHardErrorProcessing = 0x388,
    LastThreadExitStatus = 0x38c,
    PrefetchTrace = 0x390,
    LockedPagesList = 0x398,
    ReadOperationCount = 0x3a0,
    WriteOperationCount = 0x3a8,
    OtherOperationCount = 0x3b0,
    ReadTransferCount = 0x3b8,
    WriteTransferCount = 0x3c0,
    OtherTransferCount = 0x3c8,
    CommitChargeLimit = 0x3d0,
    CommitCharge = 0x3d8,
    CommitChargePeak = 0x3e0,
    Vm = 0x400,
    MmProcessLinks = 0x540,
    ModifiedPageCount = 0x550,
    ExitStatus = 0x554,
    VadRoot = 0x558,
    VadHint = 0x560,
    VadCount = 0x568,
    VadPhysicalPages = 0x570,
    VadPhysicalPagesLimit = 0x578,
    AlpcContext = 0x580,
    TimerResolutionLink = 0x5a0,
    TimerResolutionStackRecord = 0x5b0,
    RequestedTimerResolution = 0x5b8,
    SmallestTimerResolution = 0x5bc,
    ExitTime = 0x5c0,
    InvertedFunctionTable = 0x5c8,
    InvertedFunctionTableLock = 0x5d0,
    ActiveThreadsHighWatermark = 0x5d8,
    LargePrivateVadCount = 0x5dc,
    ThreadListLock = 0x5e0,
    WnfContext = 0x5e8,
    ServerSilo = 0x5f0,
    SignatureLevel = 0x5f8,
    SectionSignatureLevel = 0x5f9,
    Protection = 0x5fa,
    HangCount = 0x5fb,
    Flags3 = 0x5fc,
    DeviceAsid = 0x600,
    SvmData = 0x608,
    SvmProcessLock = 0x610,
    SvmLock = 0x618,
    SvmProcessDeviceListHead = 0x620,
    LastFreezeInterruptTime = 0x630,
    DiskCounters = 0x638,
    PicoContext = 0x640,
    EnclaveTable = 0x648,
    EnclaveNumber = 0x650,
    EnclaveLock = 0x658,
    HighPriorityFaultsAllowed = 0x660,
    EnergyContext = 0x668,
    VmContext = 0x670,
    SequenceNumber = 0x678,
    CreateInterruptTime = 0x680,
    CreateUnbiasedInterruptTime = 0x688,
    TotalUnbiasedFrozenTime = 0x690,
    LastAppStateUpdateTime = 0x698,
    LastAppStateUptime = 0x6a0,
    SharedCommitCharge = 0x6a8,
    SharedCommitLock = 0x6b0,
    SharedCommitLinks = 0x6b8,
    AllowedCpuSetsIndirect = 0x6c8,
    DefaultCpuSetsIndirect = 0x6d0,
    DiskIoAttribution = 0x6d8,
    DxgProcess = 0x6e0,
    Win32KFilterSet = 0x6e8,
    Machine = 0x6ec,
    MmSlabIdentity = 0x6ee,
    Spare0 = 0x6ef,
    ProcessTimerDelay = 0x6f0,
    KTimerSets = 0x6f8,
    KTimer2Sets = 0x6fc,
    ThreadTimerSets = 0x700,
    VirtualTimerListLock = 0x708,
    VirtualTimerListHead = 0x710,
    WakeInfo = 0x720,
    MitigationFlags = 0x750,
    MitigationFlags2 = 0x754,
    PartitionObject = 0x758,
    SecurityDomain = 0x760,
    ParentSecurityDomain = 0x768,
    CoverageSamplerContext = 0x770,
    MmHotPatchContext = 0x778,
    DynamicEHContinuationTargetsTree = 0x780,
    DynamicEHContinuationTargetsLock = 0x788,
    DynamicEnforcedCetCompatibleRanges = 0x790,
    DisabledComponentFlags = 0x7a0,
    PageCombineSequence = 0x7a4,
    EnableOptionalXStateFeaturesLock = 0x7a8,
    PathRedirectionHashes = 0x7b0,
    SyscallProvider = 0x7b8,
    SyscallProviderProcessLinks = 0x7c0,
    SyscallProviderDispatchContext = 0x7d0,
    MitigationFlags3Values = 0x7d8,
    Flags4 = 0x7dc,
    SyscallUsageValues = 0x7e0,
    SupervisorDeviceAsid = 0x7e4,
    SupervisorSvmData = 0x7e8,
    NetworkCounters = 0x7f0,
    Execution = 0x7f8,
    ThreadIndexTable = 0x800,
    FreezeWorkLinks = 0x808,
    PpmPolicyLock = 0x818,
    BamPpmPolicy = 0x820,
}

#[repr(isize)]
pub enum PebOffset {
    InheritedAddressSpace = 0x000,
    ReadImageFileExecOptions = 0x001,
    BeingDebugged = 0x002,
    BitField = 0x003,
    Padding0 = 0x004,
    Mutant = 0x008,
    ImageBaseAddress = 0x010,
    Ldr = 0x018,
    ProcessParameters = 0x020,
    SubSystemData = 0x028,
    ProcessHeap = 0x030,
    FastPebLock = 0x038,
    AtlThunkSListPtr = 0x040,
    IFEOKey = 0x048,
    ProcessInJob = 0x050,
    Padding1 = 0x054,
    KernelCallbackTable = 0x058,
    SystemReserved = 0x060,
    AtlThunkSListPtr32 = 0x064,
    ApiSetMap = 0x068,
    TlsExpansionCounter = 0x070,
    Padding2 = 0x074,
    TlsBitmap = 0x078,
    TlsBitmapBits = 0x080,
    ReadOnlySharedMemoryBase = 0x088,
    SharedData = 0x090,
    ReadOnlyStaticServerData = 0x098,
    AnsiCodePageData = 0x0a0,
    OemCodePageData = 0x0a8,
    UnicodeCaseTableData = 0x0b0,
    NumberOfProcessors = 0x0b8,
    NtGlobalFlag = 0x0bc,
    CriticalSectionTimeout = 0x0c0,
    HeapSegmentReserve = 0x0c8,
    HeapSegmentCommit = 0x0d0,
    HeapDeCommitTotalFreeThreshold = 0x0d8,
    HeapDeCommitFreeBlockThreshold = 0x0e0,
    NumberOfHeaps = 0x0e8,
    MaximumNumberOfHeaps = 0x0ec,
    ProcessHeaps = 0x0f0,
    GdiSharedHandleTable = 0x0f8,
    ProcessStarterHelper = 0x100,
    GdiDCAttributeList = 0x108,
    Padding3 = 0x10c,
    LoaderLock = 0x110,
    OSMajorVersion = 0x118,
    OSMinorVersion = 0x11c,
    OSBuildNumber = 0x120,
    OSCSDVersion = 0x122,
    OSPlatformId = 0x124,
    ImageSubsystem = 0x128,
    ImageSubsystemMajorVersion = 0x12c,
    ImageSubsystemMinorVersion = 0x130,
    Padding4 = 0x134,
    ActiveProcessAffinityMask = 0x138,
    GdiHandleBuffer = 0x140,
    PostProcessInitRoutine = 0x230,
    TlsExpansionBitmap = 0x238,
    TlsExpansionBitmapBits = 0x240,
    SessionId = 0x2c0,
    Padding5 = 0x2c4,
    AppCompatFlags = 0x2c8,
    AppCompatFlagsUser = 0x2d0,
    PShimData = 0x2d8,
    AppCompatInfo = 0x2e0,
    CSDVersion = 0x2e8,
    ActivationContextData = 0x2f8,
    ProcessAssemblyStorageMap = 0x300,
    SystemDefaultActivationContextData = 0x308,
    SystemAssemblyStorageMap = 0x310,
    MinimumStackCommit = 0x318,
    SparePointers = 0x320,
    PatchLoaderData = 0x330,
    ChpeV2ProcessInfo = 0x338,
    AppModelFeatureState = 0x340,
    SpareUlongs = 0x344,
    ActiveCodePage = 0x34c,
    OemCodePage = 0x34e,
    UseCaseMapping = 0x350,
    UnusedNlsField = 0x352,
    WerRegistrationData = 0x358,
    WerShipAssertPtr = 0x360,
    EcCodeBitMap = 0x368,
    PImageHeaderHash = 0x370,
    HeapTracingEnabled = 0x378,
    Padding6 = 0x37c,
    CsrServerReadOnlySharedMemoryBase = 0x380,
    TppWorkerpListLock = 0x388,
    TppWorkerpList = 0x390,
    WaitOnAddressHashTable = 0x3a0,
    TelemetryCoverageHeader = 0x7a0,
    CloudFileFlags = 0x7a8,
    CloudFileDiagFlags = 0x7ac,
    PlaceholderCompatibilityMode = 0x7b0,
    PlaceholderCompatibilityModeReserved = 0x7b1,
    LeapSecondData = 0x7b8,
    Reserved = 0x7c0,
    NtGlobalFlag2 = 0x7c4,
    ExtendedFeatureDisableMask = 0x7c8,
    Win32ClientProcInfo = 0x7d0,
}

#[repr(C)]
struct RTL_USER_PROCESS_PARAMETERS {
    pub maximum_length: u32,
    pub length: u32,
    pub flags: u32,
    pub debug_flags: u32,
    pub console_handle: PVOID,
    pub console_flags: u32,
    pub standard_input: PVOID,
    pub standard_output: PVOID,
    pub standard_error: PVOID,
    pub current_directory: CURDIR,
    pub dll_path: UNICODE_STRING,
    pub image_path_name: UNICODE_STRING,
    pub command_line: UNICODE_STRING,
    pub environment: PVOID,
    pub starting_x: u32,
    pub starting_y: u32,
    pub count_x: u32,
    pub count_y: u32,
    pub count_chars_x: u32,
    pub count_chars_y: u32,
    pub fill_attribute: u32,
    pub window_flags: u32,
    pub show_window_flags: u32,
    pub window_title: UNICODE_STRING,
    pub desktop_info: UNICODE_STRING,
    pub shell_info: UNICODE_STRING,
    pub runtime_data: UNICODE_STRING,
    pub current_directores: [RTL_DRIVE_LETTER_CURDIR; 32],
    pub environment_size: u64,
    pub environment_version: u64,
    pub package_dependency_data: PVOID,
    pub process_group_id: u32,
    pub loader_threads: u32,
    pub redirection_dll_name: UNICODE_STRING,
    pub heap_partition_name: UNICODE_STRING,
    pub default_threadpool_cpu_set_masks: *mut u64,
    pub default_threadpool_cpu_set_mask_count: u32,
    pub default_threadpool_thread_maximum: u32,
    pub heap_memory_type_mask: u32,
    pub attribute_list: PVOID,
}

#[repr(C)]
struct RTL_DRIVE_LETTER_CURDIR {
    pub flags: u16,
    pub length: u16,
    pub time_stamp: u32,
    pub dos_path: UNICODE_STRING,
}

#[repr(C)]
struct CURDIR {
    pub dos_path: UNICODE_STRING,
    pub handle: HANDLE,
}
