[package]
name = "um"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
windows-core = "0.62.2"
shared = { path = "../shared/"}

[dependencies.windows]
version = "0.62.2"
features = ["Win32", "Win32_System", "Win32_System_Console", "Win32_UI", "Win32_UI_Input", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_Threading", "Win32_Security", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader", "Win32_Storage", "Win32_Storage_FileSystem", "Win32_Graphics", "Win32_Graphics_Gdi", "Win32_Graphics_OpenGL", "Win32_System_Diagnostics", "Win32_System_Diagnostics_ToolHelp", "Win32_System_SystemServices", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct3D", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common", "Win32_Graphics_Direct3D_Fxc", "Win32_System_ProcessStatus", "Win32_System_Memory", "Win32_System_IO"]
